USE [Bookstore1]
GO

/****** Object:  Table [ventas].[FACTURA]    Script Date: 17/12/2019 14:30:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [ventas].[FACTURA](
	[IDFACTURA] [int] NOT NULL,
	[IDCLIENTE] [int] NULL,
	[FECHA] [datetime] NOT NULL,
	[TIPOFAC] [varchar](10) NULL,
	[MONTOTOTAL] [numeric](8, 2) NULL,
	[IDTARJETA] [int] NULL,
 CONSTRAINT [PK_FACTURA] PRIMARY KEY CLUSTERED 
(
	[IDFACTURA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [Bookstore_Data]
) ON [Bookstore_Data]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [ventas].[FACTURA]  WITH CHECK ADD  CONSTRAINT [FK_FACTURA_POSEE] FOREIGN KEY([IDCLIENTE], [IDTARJETA])
REFERENCES [dbo].[TARJETACREDITO] ([IDCLIENTE], [IDTARJETA])
GO

ALTER TABLE [ventas].[FACTURA] CHECK CONSTRAINT [FK_FACTURA_POSEE]
GO

ALTER TABLE [ventas].[FACTURA]  WITH CHECK ADD  CONSTRAINT [FK_FACTURA_REALIZA_CLIENTE] FOREIGN KEY([IDCLIENTE])
REFERENCES [ventas].[CLIENTE] ([IDCLIENTE])
GO

ALTER TABLE [ventas].[FACTURA] CHECK CONSTRAINT [FK_FACTURA_REALIZA_CLIENTE]
GO

ALTER TABLE [ventas].[FACTURA]  WITH CHECK ADD  CONSTRAINT [FK_FACTURA_TIENE] FOREIGN KEY([IDCLIENTE])
REFERENCES [ventas].[CLIENTE] ([IDCLIENTE])
GO

ALTER TABLE [ventas].[FACTURA] CHECK CONSTRAINT [FK_FACTURA_TIENE]
GO


